server:
  port: 8081
spring:
    datasource:
      password: root
      username: root
      url: jdbc:mysql://localhost:3306/server_db
      mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
    jpa:
      hibernate:
        ddl-auto: create
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            show-sql: true

